name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: sudo apt-get install -y nasm xorriso mtools grub-pc-bin python3 python3-png gcc-i686-*
      
    - name: Build (4 cores)
      run: make -j2
